# Generated by Django 6.0.5 on 2026-05-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crediapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('ready', 'Ready Payment'), ('credit', 'Pay Later')], max_length=20)),
                ('repayment_schedule', models.CharField(blank=True, choices=[('weekly', 'First Week'), ('2_weeks', 'Second Week'), ('3_weeks', 'Third Week'), ('monthly', 'Monthly'), ('custom', 'Custom Date')], max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
